// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413121500_AddBillOfMaterials")]
    partial class AddBillOfMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.BillOfMaterial", b =>
                {
                    b.Property<int>("ParentArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentArticleId")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedScrap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ScrapFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ScrapPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UmId")
                        .HasColumnType("int");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ParentArticleId", "ComponentArticleId");

                    b.HasIndex("ComponentArticleId");

                    b.HasIndex("UmId");

                    b.ToTable("BillOfMaterials", (string)null);

                    b.HasCheckConstraint("CHK_QuantityType", "QuantityType IN ('PHYSICAL', 'PERCENTAGE')");
                });

            modelBuilder.Entity("Api.Models.BillOfMaterial", b =>
                {
                    b.HasOne("Api.Models.Article", "ComponentArticle")
                        .WithMany("AsComponentArticle")
                        .HasForeignKey("ComponentArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.Article", "ParentArticle")
                        .WithMany("AsParentArticle")
                        .HasForeignKey("ParentArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.MeasureUnit", "UM")
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("UmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentArticle");

                    b.Navigation("ParentArticle");

                    b.Navigation("UM");
                });

            modelBuilder.Entity("Api.Models.Article", b =>
                {
                    b.Navigation("AsComponentArticle");

                    b.Navigation("AsParentArticle");
                });

            modelBuilder.Entity("Api.Models.MeasureUnit", b =>
                {
                    b.Navigation("BillOfMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
